import React, { useState, useEffect } from 'react';
import { 
  HelpCircle, 
  Play, 
  Trophy, 
  Sparkles, 
  Clock, 
  Plus, 
  Award,
  CheckCircle2,
  Calendar
} from 'lucide-react';
import { Quiz, QuizResult } from '../../types';
import { QuizTaker } from './QuizTaker';
import { api } from '../../services/api';
import { useLanguage } from '../../context/LanguageContext';

interface QuizHubProps {
  onRefreshStats?: () => void;
}

export const QuizHub: React.FC<QuizHubProps> = ({ onRefreshStats }) => {
  const { t } = useLanguage();
  const [quizzes, setQuizzes] = useState<Quiz[]>([]);
  const [results, setResults] = useState<QuizResult[]>([]);
  const [activeQuiz, setActiveQuiz] = useState<Quiz | null>(null);
  const [loading, setLoading] = useState(true);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newTopic, setNewTopic] = useState('');
  const [newSubject, setNewSubject] = useState('');
  const [newDifficulty, setNewDifficulty] = useState<'easy' | 'medium' | 'hard'>('medium');
  const [newCount, setNewCount] = useState(5);
  const [generating, setGenerating] = useState(false);

  const loadData = async () => {
    try {
      setLoading(true);
      const [quizRes, resultRes] = await Promise.all([
        api.getQuizzes(),
        api.getQuizResults()
      ]);
      setQuizzes(quizRes.quizzes || []);
      setResults(resultRes.results || []);
    } catch (err) {
      console.error('Failed to load quiz data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleGenerateQuiz = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTopic.trim()) return;
    setGenerating(true);
    try {
      const res = await api.generateQuiz({
        topic: newTopic.trim(),
        subject: newSubject.trim() || undefined,
        difficulty: newDifficulty,
        questionCount: Number(newCount),
        autoSave: true,
      });

      setQuizzes(prev => [res.quiz, ...prev]);
      setShowCreateModal(false);
      setNewTopic('');
      setNewSubject('');
      setActiveQuiz(res.quiz);
    } catch (err: any) {
      alert(err.message || 'Failed to generate quiz');
    } finally {
      setGenerating(false);
    }
  };

  if (activeQuiz) {
    return (
      <QuizTaker
        quiz={activeQuiz}
        onBack={() => {
          setActiveQuiz(null);
          loadData();
        }}
        onQuizCompleted={() => {
          if (onRefreshStats) onRefreshStats();
        }}
      />
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 md:p-8 bg-zinc-50 dark:bg-zinc-950">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Header Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase tracking-wider bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
                {t('quizSystem')}
              </span>
            </div>
            <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
              {t('quizSystem')}
            </h1>
            <p className="text-sm text-zinc-600 dark:text-zinc-400 mt-1">
              Take timed assessments generated by Gemini AI with in-depth feedback and earn XP.
            </p>
          </div>

          <button
            onClick={() => setShowCreateModal(true)}
            className="flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs shadow-md shadow-indigo-600/20 transition-all self-start sm:self-auto"
          >
            <Plus className="w-4 h-4" />
                <span>{t('studyTools')}</span>
          </button>
        </div>

        {/* Quizzes List Grid */}
        <div className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-zinc-400 dark:text-zinc-500">
            {t('quizSystem')} ({quizzes.length})
          </h2>

          {loading ? (
            <div className="text-center py-12 text-zinc-400 text-xs">Loading quizzes...</div>
          ) : quizzes.length === 0 ? (
            <div className="p-8 text-center rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800">
              <HelpCircle className="w-10 h-10 text-zinc-400 mx-auto mb-2 opacity-50" />
              <p className="text-sm font-semibold text-zinc-800 dark:text-zinc-200">No quizzes available yet</p>
              <p className="text-xs text-zinc-500 mt-1">Generate your first active-recall test now!</p>
              <button
                onClick={() => setShowCreateModal(true)}
                className="mt-4 px-4 py-2 bg-indigo-600 text-white text-xs font-semibold rounded-xl"
              >
                Create Quiz
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {quizzes.map(quiz => {
                const pastResults = results.filter(r => r.quizId === quiz.id);
                const bestScore = pastResults.length > 0
                  ? Math.max(...pastResults.map(r => r.percentage))
                  : null;

                return (
                  <div
                    key={quiz.id}
                    id={`quiz-card-${quiz.id}`}
                    className="p-5 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 hover:border-indigo-500/50 shadow-xs hover:shadow-md transition-all flex flex-col justify-between"
                  >
                    <div>
                      <div className="flex items-center justify-between gap-2 mb-2">
                        <span className={`px-2 py-0.5 rounded text-[10px] uppercase font-bold ${
                          quiz.difficulty === 'easy' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' :
                          quiz.difficulty === 'hard' ? 'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300' :
                          'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300'
                        }`}>
                          {quiz.difficulty || 'medium'}
                        </span>

                        <div className="flex items-center gap-1 text-[11px] text-zinc-400 font-mono">
                          <Clock className="w-3 h-3" />
                          <span>{quiz.timeLimitMinutes || 5} min</span>
                        </div>
                      </div>

                      <h3 className="font-bold text-base text-zinc-900 dark:text-zinc-100 leading-snug">
                        {quiz.title}
                      </h3>

                      <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">
                        {quiz.topicName || 'General Studies'} • {quiz.questions?.length || 0} Questions
                      </p>

                      {/* Best Score Pill */}
                      {bestScore !== null && (
                        <div className="mt-3 flex items-center gap-1.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/40 px-2.5 py-1 rounded-lg border border-emerald-200 dark:border-emerald-800/40 self-start inline-flex">
                          <Trophy className="w-3.5 h-3.5" />
                          <span>Best Score: {bestScore}%</span>
                        </div>
                      )}
                    </div>

                    <button
                      onClick={() => setActiveQuiz(quiz)}
                      className="w-full mt-4 flex items-center justify-center gap-2 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-xs transition-colors"
                    >
                      <Play className="w-3.5 h-3.5 fill-white" />
                      <span>{bestScore !== null ? 'Retake Quiz' : 'Start Assessment'}</span>
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Modal: Generate New Quiz */}
        {showCreateModal && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-xs z-50 flex items-center justify-center p-4">
            <div className="w-full max-w-md bg-white dark:bg-zinc-900 rounded-2xl shadow-2xl border border-zinc-200 dark:border-zinc-800 p-6 space-y-4 animate-in fade-in zoom-in-95 duration-200">
              <div className="flex items-center justify-between border-b border-zinc-100 dark:border-zinc-800 pb-3">
                <h3 className="font-bold text-base text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-indigo-500" />
                  Generate AI Assessment Quiz
                </h3>
                <button
                  onClick={() => setShowCreateModal(false)}
                  className="text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200"
                >
                  ✕
                </button>
              </div>

              <form onSubmit={handleGenerateQuiz} className="space-y-3">
                <div>
                  <label className="block text-xs font-semibold text-zinc-700 dark:text-zinc-300 mb-1">
                    Quiz Topic / Concept *
                  </label>
                  <input
                    type="text"
                    required
                    value={newTopic}
                    onChange={e => setNewTopic(e.target.value)}
                    placeholder="e.g. Organic Chemistry Reactions, React Lifecycle Hooks"
                    className="w-full px-3 py-2 text-sm rounded-xl bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 text-zinc-900 dark:text-zinc-100 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-zinc-700 dark:text-zinc-300 mb-1">
                    Subject / Category
                  </label>
                  <input
                    type="text"
                    value={newSubject}
                    onChange={e => setNewSubject(e.target.value)}
                    placeholder="e.g. Science, Tech, Medical"
                    className="w-full px-3 py-2 text-sm rounded-xl bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 text-zinc-900 dark:text-zinc-100 focus:outline-none"
                  />
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="block text-xs font-semibold text-zinc-700 dark:text-zinc-300 mb-1">Difficulty</label>
                    <select
                      value={newDifficulty}
                      onChange={e => setNewDifficulty(e.target.value as any)}
                      className="w-full px-3 py-2 text-sm rounded-xl bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 text-zinc-900 dark:text-zinc-100"
                    >
                      <option value="easy">Easy</option>
                      <option value="medium">Medium</option>
                      <option value="hard">Hard</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-zinc-700 dark:text-zinc-300 mb-1">Questions</label>
                    <select
                      value={newCount}
                      onChange={e => setNewCount(Number(e.target.value))}
                      className="w-full px-3 py-2 text-sm rounded-xl bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 text-zinc-900 dark:text-zinc-100"
                    >
                      <option value={3}>3 Questions</option>
                      <option value={5}>5 Questions</option>
                      <option value={8}>8 Questions</option>
                      <option value={10}>10 Questions</option>
                    </select>
                  </div>
                </div>

                <button
                  type="submit"
                  disabled={generating}
                  className="w-full mt-3 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs shadow-md shadow-indigo-600/20 flex items-center justify-center gap-2"
                >
                  {generating ? 'Generating Quiz...' : 'Generate & Start Quiz'}
                </button>
              </form>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
