import React, { createContext, useContext, useMemo, useState } from 'react';
import { DEFAULT_RESPONSE_LANGUAGE, getResponseLanguage, ResponseLanguage } from '../types/languages';

type TranslationKey =
  | 'aiStudyChat' | 'studyTools' | 'quizSystem' | 'flashcards' | 'analytics' | 'subjects' | 'notes'
  | 'planner' | 'documents' | 'settings' | 'newChat' | 'newStudyChat' | 'recentChats'
  | 'searchConversations' | 'noConversations' | 'save' | 'delete' | 'rename' | 'student'
  | 'signIn' | 'logOut' | 'responseLanguage' | 'selectStudyMode' | 'attachDoc'
  | 'groundedMaterials' | 'generatingResponse' | 'latest' | 'welcomeStudy' | 'studyIntro'
  | 'accountPreferences' | 'profileSettings' | 'displayName' | 'academicGoal' | 'defaultStudyMode'
  | 'savePreferences' | 'changesSaved' | 'dashboard' | 'startTutor' | 'takeAssessment'
  | 'studyStreak' | 'days' | 'dailyGoal' | 'levelProgress' | 'quizzesTaken' | 'completed'
  | 'flashcardMastery' | 'cards' | 'recentSessions' | 'viewAll';

const translations: Record<string, Partial<Record<TranslationKey, string>>> = {
  en: {
    aiStudyChat: 'AI Study Chat', studyTools: 'Study Tools Hub', quizSystem: 'Quiz System', flashcards: 'Flashcards',
    analytics: 'Study Analytics', subjects: 'Subjects & Syllabus', notes: 'Study Notes', planner: 'Study Planner',
    documents: 'Documents & Uploads', settings: 'Preferences & AI', newChat: 'New Chat', newStudyChat: 'New Study Chat',
    recentChats: 'Recent Chats', searchConversations: 'Search conversations...', noConversations: 'No conversations found',
    save: 'Save', delete: 'Delete', rename: 'Rename', student: 'Student', signIn: 'Sign In', logOut: 'Log out',
    responseLanguage: 'Response language', selectStudyMode: 'Select AI Study Mode', attachDoc: 'Attach Doc',
    groundedMaterials: 'Grounded Study Materials', generatingResponse: 'Generating response', latest: 'Latest',
    welcomeStudy: 'How can I assist your study session today?', studyIntro: 'Select a specialized study mode, upload revision documents, or choose a starter topic below.',
    accountPreferences: 'Account & Preferences', profileSettings: 'Student Profile & AI Settings', displayName: 'Display Name',
    academicGoal: 'Primary Academic Goal', defaultStudyMode: 'Default AI Study Mode', savePreferences: 'Save Preferences',
    changesSaved: 'Changes Saved!', dashboard: 'Study Dashboard', startTutor: 'Start AI Tutor', takeAssessment: 'Take Assessment',
    studyStreak: 'Study Streak', days: 'Days', dailyGoal: 'Daily goal achieved today!', levelProgress: 'Level & Progress',
    quizzesTaken: 'Quizzes Taken', completed: 'Completed', flashcardMastery: 'Flashcard Mastery', cards: 'Cards',
    recentSessions: 'Recent AI Tutoring Sessions', viewAll: 'View All',
  },
  hi: {
    aiStudyChat: 'AI अध्ययन चैट', studyTools: 'अध्ययन उपकरण', quizSystem: 'क्विज़ प्रणाली', flashcards: 'फ्लैशकार्ड', analytics: 'अध्ययन विश्लेषण',
    subjects: 'विषय और पाठ्यक्रम', notes: 'अध्ययन नोट्स', planner: 'अध्ययन योजनाकार', documents: 'दस्तावेज़ और अपलोड', settings: 'प्राथमिकताएँ और AI',
    newChat: 'नई चैट', newStudyChat: 'नई अध्ययन चैट', recentChats: 'हाल की चैट', searchConversations: 'बातचीत खोजें...', noConversations: 'कोई बातचीत नहीं मिली',
    save: 'सहेजें', delete: 'हटाएँ', rename: 'नाम बदलें', student: 'विद्यार्थी', signIn: 'साइन इन', logOut: 'लॉग आउट', responseLanguage: 'उत्तर की भाषा',
    selectStudyMode: 'AI अध्ययन मोड चुनें', attachDoc: 'दस्तावेज़ जोड़ें', groundedMaterials: 'अध्ययन सामग्री', generatingResponse: 'उत्तर तैयार हो रहा है', latest: 'नवीनतम',
    welcomeStudy: 'आज मैं आपके अध्ययन सत्र में कैसे सहायता कर सकता हूँ?', studyIntro: 'अध्ययन मोड चुनें, दस्तावेज़ अपलोड करें या नीचे कोई विषय चुनें।',
    accountPreferences: 'खाता और प्राथमिकताएँ', profileSettings: 'विद्यार्थी प्रोफ़ाइल और AI सेटिंग्स', displayName: 'प्रदर्शित नाम', academicGoal: 'मुख्य शैक्षणिक लक्ष्य',
    defaultStudyMode: 'डिफ़ॉल्ट AI अध्ययन मोड', savePreferences: 'प्राथमिकताएँ सहेजें', changesSaved: 'परिवर्तन सहेजे गए!', dashboard: 'अध्ययन डैशबोर्ड',
    startTutor: 'AI ट्यूटर शुरू करें', takeAssessment: 'मूल्यांकन दें', studyStreak: 'अध्ययन क्रम', days: 'दिन', dailyGoal: 'आज का लक्ष्य पूरा हुआ!',
    levelProgress: 'स्तर और प्रगति', quizzesTaken: 'दिए गए क्विज़', completed: 'पूर्ण', flashcardMastery: 'फ्लैशकार्ड दक्षता', cards: 'कार्ड', recentSessions: 'हाल के AI अध्ययन सत्र', viewAll: 'सभी देखें',
  },
  bn: { aiStudyChat: 'AI স্টাডি চ্যাট', studyTools: 'স্টাডি টুলস', quizSystem: 'কুইজ সিস্টেম', flashcards: 'ফ্ল্যাশকার্ড', analytics: 'স্টাডি বিশ্লেষণ', subjects: 'বিষয় ও সিলেবাস', notes: 'স্টাডি নোট', planner: 'স্টাডি প্ল্যানার', documents: 'নথি ও আপলোড', settings: 'পছন্দ ও AI', newChat: 'নতুন চ্যাট', newStudyChat: 'নতুন স্টাডি চ্যাট', recentChats: 'সাম্প্রতিক চ্যাট', searchConversations: 'কথোপকথন খুঁজুন...', noConversations: 'কোনও কথোপকথন পাওয়া যায়নি', save: 'সংরক্ষণ', delete: 'মুছুন', rename: 'নাম বদলান', student: 'শিক্ষার্থী', signIn: 'সাইন ইন', logOut: 'লগ আউট', responseLanguage: 'উত্তরের ভাষা', selectStudyMode: 'AI স্টাডি মোড বাছুন', attachDoc: 'নথি যোগ করুন', groundedMaterials: 'স্টাডি উপকরণ', generatingResponse: 'উত্তর তৈরি হচ্ছে', latest: 'সর্বশেষ', welcomeStudy: 'আজ আপনার স্টাডি সেশনে কীভাবে সাহায্য করব?', studyIntro: 'স্টাডি মোড বাছুন, নথি আপলোড করুন বা নিচে বিষয় বাছুন।', accountPreferences: 'অ্যাকাউন্ট ও পছন্দ', profileSettings: 'শিক্ষার্থী প্রোফাইল ও AI সেটিংস', displayName: 'প্রদর্শিত নাম', academicGoal: 'প্রধান শিক্ষাগত লক্ষ্য', defaultStudyMode: 'ডিফল্ট AI স্টাডি মোড', savePreferences: 'পছন্দ সংরক্ষণ করুন', changesSaved: 'পরিবর্তন সংরক্ষিত!', dashboard: 'স্টাডি ড্যাশবোর্ড', startTutor: 'AI টিউটর শুরু করুন', takeAssessment: 'মূল্যায়ন দিন', studyStreak: 'স্টাডি স্ট্রিক', days: 'দিন', dailyGoal: 'আজকের লক্ষ্য পূর্ণ!', levelProgress: 'স্তর ও অগ্রগতি', quizzesTaken: 'দেওয়া কুইজ', completed: 'সম্পূর্ণ', flashcardMastery: 'ফ্ল্যাশকার্ড দক্ষতা', cards: 'কার্ড', recentSessions: 'সাম্প্রতিক AI সেশন', viewAll: 'সব দেখুন' },
  te: { aiStudyChat: 'AI అధ్యయన చాట్', studyTools: 'అధ్యయన సాధనాలు', quizSystem: 'క్విజ్ వ్యవస్థ', flashcards: 'ఫ్లాష్‌కార్డులు', analytics: 'అధ్యయన విశ్లేషణ', subjects: 'విషయాలు మరియు సిలబస్', notes: 'అధ్యయన నోట్స్', planner: 'అధ్యయన ప్లానర్', documents: 'పత్రాలు మరియు అప్‌లోడ్‌లు', settings: 'ప్రాధాన్యతలు మరియు AI', newChat: 'కొత్త చాట్', newStudyChat: 'కొత్త అధ్యయన చాట్', recentChats: 'ఇటీవలి చాట్‌లు', searchConversations: 'సంభాషణలను వెతకండి...', noConversations: 'సంభాషణలు లేవు', save: 'భద్రపరచు', delete: 'తొలగించు', rename: 'పేరు మార్చు', student: 'విద్యార్థి', signIn: 'సైన్ ఇన్', logOut: 'లాగ్ అవుట్', responseLanguage: 'సమాధాన భాష', selectStudyMode: 'AI అధ్యయన మోడ్ ఎంచుకోండి', attachDoc: 'పత్రం జోడించు', groundedMaterials: 'అధ్యయన సామగ్రి', generatingResponse: 'సమాధానం తయారవుతోంది', latest: 'తాజా', welcomeStudy: 'ఈరోజు మీ అధ్యయన సెషన్‌కు ఎలా సహాయపడగలను?', studyIntro: 'మోడ్ ఎంచుకోండి, పత్రాలను అప్‌లోడ్ చేయండి లేదా అంశాన్ని ఎంచుకోండి.', accountPreferences: 'ఖాతా మరియు ప్రాధాన్యతలు', profileSettings: 'విద్యార్థి ప్రొఫైల్ మరియు AI సెట్టింగ్‌లు', displayName: 'ప్రదర్శన పేరు', academicGoal: 'ప్రధాన విద్యా లక్ష్యం', defaultStudyMode: 'డిఫాల్ట్ AI అధ్యయన మోడ్', savePreferences: 'ప్రాధాన్యతలను భద్రపరచు', changesSaved: 'మార్పులు భద్రపరచబడ్డాయి!', dashboard: 'అధ్యయన డ్యాష్‌బోర్డ్', startTutor: 'AI ట్యూటర్ ప్రారంభించు', takeAssessment: 'మూల్యాంకనం రాయండి', studyStreak: 'అధ్యయన పరంపర', days: 'రోజులు', dailyGoal: 'ఈరోజు లక్ష్యం పూర్తయింది!', levelProgress: 'స్థాయి మరియు పురోగతి', quizzesTaken: 'క్విజ్‌లు', completed: 'పూర్తయింది', flashcardMastery: 'ఫ్లాష్‌కార్డ్ నైపుణ్యం', cards: 'కార్డులు', recentSessions: 'ఇటీవలి AI సెషన్‌లు', viewAll: 'అన్నీ చూడండి' },
  ta: { aiStudyChat: 'AI படிப்பு அரட்டை', studyTools: 'படிப்புக் கருவிகள்', quizSystem: 'வினாடி வினா அமைப்பு', flashcards: 'ஃபிளாஷ்கார்டுகள்', analytics: 'படிப்பு பகுப்பாய்வு', subjects: 'பாடங்கள் மற்றும் பாடத்திட்டம்', notes: 'படிப்பு குறிப்புகள்', planner: 'படிப்பு திட்டமிடுபவர்', documents: 'ஆவணங்கள் மற்றும் பதிவேற்றங்கள்', settings: 'விருப்பங்கள் மற்றும் AI', newChat: 'புதிய அரட்டை', newStudyChat: 'புதிய படிப்பு அரட்டை', recentChats: 'சமீபத்திய அரட்டைகள்', searchConversations: 'உரையாடல்களைத் தேடுங்கள்...', noConversations: 'உரையாடல்கள் இல்லை', save: 'சேமி', delete: 'நீக்கு', rename: 'மறுபெயரிடு', student: 'மாணவர்', signIn: 'உள்நுழை', logOut: 'வெளியேறு', responseLanguage: 'பதில் மொழி', selectStudyMode: 'AI படிப்பு முறையைத் தேர்ந்தெடுக்கவும்', attachDoc: 'ஆவணத்தை இணைக்கவும்', groundedMaterials: 'படிப்பு ஆதாரங்கள்', generatingResponse: 'பதில் உருவாகிறது', latest: 'சமீபத்திய', welcomeStudy: 'இன்று உங்கள் படிப்பு அமர்வில் நான் எவ்வாறு உதவலாம்?', studyIntro: 'படிப்பு முறையைத் தேர்ந்தெடுக்கவும், ஆவணங்களைப் பதிவேற்றவும் அல்லது தலைப்பைத் தேர்ந்தெடுக்கவும்.', accountPreferences: 'கணக்கு மற்றும் விருப்பங்கள்', profileSettings: 'மாணவர் சுயவிவரம் மற்றும் AI அமைப்புகள்', displayName: 'காட்சிப் பெயர்', academicGoal: 'முதன்மை கல்வி இலக்கு', defaultStudyMode: 'இயல்புநிலை AI படிப்பு முறை', savePreferences: 'விருப்பங்களைச் சேமிக்கவும்', changesSaved: 'மாற்றங்கள் சேமிக்கப்பட்டன!', dashboard: 'படிப்பு டாஷ்போர்டு', startTutor: 'AI ஆசிரியரைத் தொடங்கு', takeAssessment: 'மதிப்பீடு எடு', studyStreak: 'படிப்பு தொடர்ச்சி', days: 'நாட்கள்', dailyGoal: 'இன்றைய இலக்கு முடிந்தது!', levelProgress: 'நிலை மற்றும் முன்னேற்றம்', quizzesTaken: 'எடுத்த வினாடி வினாக்கள்', completed: 'முடிந்தது', flashcardMastery: 'ஃபிளாஷ்கார்டு திறன்', cards: 'அட்டைகள்', recentSessions: 'சமீபத்திய AI அமர்வுகள்', viewAll: 'அனைத்தையும் காண்க' },
  mr: { aiStudyChat: 'AI अभ्यास चॅट', studyTools: 'अभ्यास साधने', quizSystem: 'क्विझ प्रणाली', flashcards: 'फ्लॅशकार्ड', analytics: 'अभ्यास विश्लेषण', subjects: 'विषय आणि अभ्यासक्रम', notes: 'अभ्यासाच्या नोंदी', planner: 'अभ्यास नियोजक', documents: 'कागदपत्रे आणि अपलोड', settings: 'प्राधान्ये आणि AI', newChat: 'नवीन चॅट', newStudyChat: 'नवीन अभ्यास चॅट', recentChats: 'अलीकडील चॅट', searchConversations: 'संभाषणे शोधा...', noConversations: 'संभाषणे सापडली नाहीत', save: 'जतन करा', delete: 'हटवा', rename: 'नाव बदला', student: 'विद्यार्थी', signIn: 'साइन इन', logOut: 'लॉग आउट', responseLanguage: 'उत्तराची भाषा', selectStudyMode: 'AI अभ्यास पद्धत निवडा', attachDoc: 'कागदपत्र जोडा', groundedMaterials: 'अभ्यास साहित्य', generatingResponse: 'उत्तर तयार होत आहे', latest: 'नवीनतम', welcomeStudy: 'आजच्या अभ्यास सत्रात मी कशी मदत करू शकतो?', studyIntro: 'अभ्यास पद्धत निवडा, कागदपत्रे अपलोड करा किंवा विषय निवडा.', accountPreferences: 'खाते आणि प्राधान्ये', profileSettings: 'विद्यार्थी प्रोफाइल आणि AI सेटिंग्ज', displayName: 'दर्शविलेले नाव', academicGoal: 'मुख्य शैक्षणिक ध्येय', defaultStudyMode: 'डीफॉल्ट AI अभ्यास पद्धत', savePreferences: 'प्राधान्ये जतन करा', changesSaved: 'बदल जतन झाले!', dashboard: 'अभ्यास डॅशबोर्ड', startTutor: 'AI ट्यूटर सुरू करा', takeAssessment: 'मूल्यांकन द्या', studyStreak: 'अभ्यास सलगता', days: 'दिवस', dailyGoal: 'आजचे ध्येय पूर्ण!', levelProgress: 'पातळी आणि प्रगती', quizzesTaken: 'दिलेल्या क्विझ', completed: 'पूर्ण', flashcardMastery: 'फ्लॅशकार्ड कौशल्य', cards: 'कार्ड', recentSessions: 'अलीकडील AI सत्रे', viewAll: 'सर्व पहा' },
  gu: { aiStudyChat: 'AI અભ્યાસ ચેટ', studyTools: 'અભ્યાસ સાધનો', quizSystem: 'ક્વિઝ સિસ્ટમ', flashcards: 'ફ્લેશકાર્ડ', analytics: 'અભ્યાસ વિશ્લેષણ', subjects: 'વિષયો અને અભ્યાસક્રમ', notes: 'અભ્યાસ નોંધો', planner: 'અભ્યાસ પ્લાનર', documents: 'દસ્તાવેજો અને અપલોડ', settings: 'પસંદગીઓ અને AI', newChat: 'નવી ચેટ', newStudyChat: 'નવી અભ્યાસ ચેટ', recentChats: 'તાજેતરની ચેટ', searchConversations: 'વાતચીત શોધો...', noConversations: 'વાતચીત મળી નથી', save: 'સાચવો', delete: 'કાઢી નાખો', rename: 'નામ બદલો', student: 'વિદ્યાર્થી', signIn: 'સાઇન ઇન', logOut: 'લૉગ આઉટ', responseLanguage: 'જવાબની ભાષા', selectStudyMode: 'AI અભ્યાસ મોડ પસંદ કરો', attachDoc: 'દસ્તાવેજ જોડો', groundedMaterials: 'અભ્યાસ સામગ્રી', generatingResponse: 'જવાબ તૈયાર થઈ રહ્યો છે', latest: 'નવીનતમ', welcomeStudy: 'આજે તમારા અભ્યાસ સત્રમાં હું કેવી રીતે મદદ કરી શકું?', studyIntro: 'મોડ પસંદ કરો, દસ્તાવેજ અપલોડ કરો અથવા વિષય પસંદ કરો.', accountPreferences: 'ખાતું અને પસંદગીઓ', profileSettings: 'વિદ્યાર્થી પ્રોફાઇલ અને AI સેટિંગ્સ', displayName: 'દર્શાવવાનું નામ', academicGoal: 'મુખ્ય શૈક્ષણિક ધ્યેય', defaultStudyMode: 'ડિફૉલ્ટ AI અભ્યાસ મોડ', savePreferences: 'પસંદગીઓ સાચવો', changesSaved: 'ફેરફારો સાચવાયા!', dashboard: 'અભ્યાસ ડેશબોર્ડ', startTutor: 'AI ટ્યુટર શરૂ કરો', takeAssessment: 'મૂલ્યાંકન આપો', studyStreak: 'અભ્યાસ સિલસિલો', days: 'દિવસ', dailyGoal: 'આજનું લક્ષ્ય પૂર્ણ!', levelProgress: 'સ્તર અને પ્રગતિ', quizzesTaken: 'આપેલી ક્વિઝ', completed: 'પૂર્ણ', flashcardMastery: 'ફ્લેશકાર્ડ કુશળતા', cards: 'કાર્ડ', recentSessions: 'તાજેતરના AI સત્રો', viewAll: 'બધું જુઓ' },
  kn: { aiStudyChat: 'AI ಅಧ್ಯಯನ ಚಾಟ್', studyTools: 'ಅಧ್ಯಯನ ಪರಿಕರಗಳು', quizSystem: 'ಕ್ವಿಜ್ ವ್ಯವಸ್ಥೆ', flashcards: 'ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್‌ಗಳು', analytics: 'ಅಧ್ಯಯನ ವಿಶ್ಲೇಷಣೆ', subjects: 'ವಿಷಯಗಳು ಮತ್ತು ಪಠ್ಯಕ್ರಮ', notes: 'ಅಧ್ಯಯನ ಟಿಪ್ಪಣಿಗಳು', planner: 'ಅಧ್ಯಯನ ಯೋಜಕ', documents: 'ದಾಖಲೆಗಳು ಮತ್ತು ಅಪ್‌ಲೋಡ್‌ಗಳು', settings: 'ಆದ್ಯತೆಗಳು ಮತ್ತು AI', newChat: 'ಹೊಸ ಚಾಟ್', newStudyChat: 'ಹೊಸ ಅಧ್ಯಯನ ಚಾಟ್', recentChats: 'ಇತ್ತೀಚಿನ ಚಾಟ್‌ಗಳು', searchConversations: 'ಸಂಭಾಷಣೆಗಳನ್ನು ಹುಡುಕಿ...', noConversations: 'ಸಂಭಾಷಣೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ', save: 'ಉಳಿಸಿ', delete: 'ಅಳಿಸಿ', rename: 'ಮರುಹೆಸರಿಸಿ', student: 'ವಿದ್ಯಾರ್ಥಿ', signIn: 'ಸೈನ್ ಇನ್', logOut: 'ಲಾಗ್ ಔಟ್', responseLanguage: 'ಪ್ರತಿಕ್ರಿಯೆಯ ಭಾಷೆ', selectStudyMode: 'AI ಅಧ್ಯಯನ ಮೋಡ್ ಆಯ್ಕೆಮಾಡಿ', attachDoc: 'ದಾಖಲೆ ಸೇರಿಸಿ', groundedMaterials: 'ಅಧ್ಯಯನ ಸಾಮಗ್ರಿ', generatingResponse: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಿದ್ಧವಾಗುತ್ತಿದೆ', latest: 'ಇತ್ತೀಚಿನ', welcomeStudy: 'ಇಂದು ನಿಮ್ಮ ಅಧ್ಯಯನ ಅವಧಿಯಲ್ಲಿ ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?', studyIntro: 'ಮೋಡ್ ಆಯ್ಕೆಮಾಡಿ, ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ.', accountPreferences: 'ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳು', profileSettings: 'ವಿದ್ಯಾರ್ಥಿ ಪ್ರೊಫೈಲ್ ಮತ್ತು AI ಸೆಟ್ಟಿಂಗ್‌ಗಳು', displayName: 'ಪ್ರದರ್ಶನ ಹೆಸರು', academicGoal: 'ಪ್ರಮುಖ ಶೈಕ್ಷಣಿಕ ಗುರಿ', defaultStudyMode: 'ಡೀಫಾಲ್ಟ್ AI ಅಧ್ಯಯನ ಮೋಡ್', savePreferences: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ', changesSaved: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ!', dashboard: 'ಅಧ್ಯಯನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', startTutor: 'AI ಟ್ಯೂಟರ್ ಪ್ರಾರಂಭಿಸಿ', takeAssessment: 'ಮೌಲ್ಯಮಾಪನ ತೆಗೆದುಕೊಳ್ಳಿ', studyStreak: 'ಅಧ್ಯಯನ ಸರಣಿ', days: 'ದಿನಗಳು', dailyGoal: 'ಇಂದಿನ ಗುರಿ ಸಾಧಿಸಲಾಗಿದೆ!', levelProgress: 'ಮಟ್ಟ ಮತ್ತು ಪ್ರಗತಿ', quizzesTaken: 'ತೆಗೆದುಕೊಂಡ ಕ್ವಿಜ್‌ಗಳು', completed: 'ಪೂರ್ಣ', flashcardMastery: 'ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್ ಪರಿಣತಿ', cards: 'ಕಾರ್ಡ್‌ಗಳು', recentSessions: 'ಇತ್ತೀಚಿನ AI ಅವಧಿಗಳು', viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ' },
  ml: { aiStudyChat: 'AI പഠന ചാറ്റ്', studyTools: 'പഠന ഉപകരണങ്ങൾ', quizSystem: 'ക്വിസ് സംവിധാനം', flashcards: 'ഫ്ലാഷ്‌കാർഡുകൾ', analytics: 'പഠന വിശകലനം', subjects: 'വിഷയങ്ങളും സിലബസും', notes: 'പഠന കുറിപ്പുകൾ', planner: 'പഠന പ്ലാനർ', documents: 'രേഖകളും അപ്‌ലോഡുകളും', settings: 'മുൻഗണനകളും AIയും', newChat: 'പുതിയ ചാറ്റ്', newStudyChat: 'പുതിയ പഠന ചാറ്റ്', recentChats: 'സമീപകാല ചാറ്റുകൾ', searchConversations: 'സംഭാഷണങ്ങൾ തിരയുക...', noConversations: 'സംഭാഷണങ്ങളൊന്നും കണ്ടെത്തിയില്ല', save: 'സേവ് ചെയ്യുക', delete: 'ഇല്ലാതാക്കുക', rename: 'പേര് മാറ്റുക', student: 'വിദ്യാർത്ഥി', signIn: 'സൈൻ ഇൻ', logOut: 'ലോഗ് ഔട്ട്', responseLanguage: 'മറുപടി ഭാഷ', selectStudyMode: 'AI പഠന മോഡ് തിരഞ്ഞെടുക്കുക', attachDoc: 'രേഖ ചേർക്കുക', groundedMaterials: 'പഠന സാമഗ്രികൾ', generatingResponse: 'മറുപടി തയ്യാറാകുന്നു', latest: 'ഏറ്റവും പുതിയത്', welcomeStudy: 'ഇന്നത്തെ പഠന സെഷനിൽ എങ്ങനെ സഹായിക്കാം?', studyIntro: 'മോഡ് തിരഞ്ഞെടുക്കുക, രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക അല്ലെങ്കിൽ വിഷയം തിരഞ്ഞെടുക്കുക.', accountPreferences: 'അക്കൗണ്ടും മുൻഗണനകളും', profileSettings: 'വിദ്യാർത്ഥി പ്രൊഫൈലും AI ക്രമീകരണങ്ങളും', displayName: 'പ്രദർശന നാമം', academicGoal: 'പ്രധാന പഠന ലക്ഷ്യം', defaultStudyMode: 'സ്ഥിര AI പഠന മോഡ്', savePreferences: 'മുൻഗണനകൾ സേവ് ചെയ്യുക', changesSaved: 'മാറ്റങ്ങൾ സേവ് ചെയ്തു!', dashboard: 'പഠന ഡാഷ്‌ബോർഡ്', startTutor: 'AI ട്യൂട്ടർ ആരംഭിക്കുക', takeAssessment: 'മൂല്യനിർണ്ണയം എടുക്കുക', studyStreak: 'പഠന തുടർച്ച', days: 'ദിവസങ്ങൾ', dailyGoal: 'ഇന്നത്തെ ലക്ഷ്യം പൂർത്തിയായി!', levelProgress: 'നിലയും പുരോഗതിയും', quizzesTaken: 'എടുത്ത ക്വിസുകൾ', completed: 'പൂർത്തിയായി', flashcardMastery: 'ഫ്ലാഷ്‌കാർഡ് കഴിവ്', cards: 'കാർഡുകൾ', recentSessions: 'സമീപകാല AI സെഷനുകൾ', viewAll: 'എല്ലാം കാണുക' },
};

interface LanguageContextValue {
  language: ResponseLanguage;
  setLanguage: (language: ResponseLanguage) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [languageCode, setLanguageCode] = useState(() => localStorage.getItem('omnistudy-response-language') || DEFAULT_RESPONSE_LANGUAGE.code);
  const language = getResponseLanguage(languageCode);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: nextLanguage => {
      setLanguageCode(nextLanguage.code);
      localStorage.setItem('omnistudy-response-language', nextLanguage.code);
      document.documentElement.lang = nextLanguage.speechCode;
    },
    t: key => translations[language.code]?.[key] || translations.en[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}